baseURL = "https://aaaab3n.moe/"
languageCode = "en-us"
title = "canarypwn"
theme = "cactus"

[params]
  [params.comments]
      enabled = true

    mathjax = true  # not required
    colortheme = "white" # dark, light, white, or classic
    rss = true # generate rss feed. default value is false
    googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default

    css = ["css/custom.css"]
    description = "Full-Stack overflow Engineer and Dependent Developer. "
    mainSection = "posts"
    showAllPostsOnHomePage = false
    postsOnHomePage = 5
    tagsOverview = true
    # googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default

[[params.social]]
  name = "github"
  link = "https://github.com/nyovelt"

[[params.social]]
  name = "email"
  link = "nyovelt@outlook.com" # no need for "mailto:" at the start

[[params.social]]
  name = "keybase"
  link = "https://keybase.io/canarypwn" # no need for "mailto:" at the start

[[params.social]]
  name = "twitter"
  link = "https://twitter.com/nyovelt" # no need for "mailto:" at the start

[[params.social]]
  name = "telegram"
  link = "https://t.me/moe_canary" # no need for "mailto:" at the start


[[menu.main]]
name = "Home"
url = "/"
weight = 1



[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "Network"
url = "/networks"
weight = 4

[[menu.main]]
name = "Notes"
url = "/notes"
weight = 5

[[menu.main]]
name = "Friends"
url = "/friends"
weight = 6

[[menu.main]]
name = "About"
url = "https://who.aaaab3n.moe/"
weight = 7

