baseURL = "http://example.org/"
languageCode = "en-us"
title = "Canarypwn"
theme = "cactus"

[params]
    mathjax = true  # not required
    colortheme = "white" # dark, light, white, or classic
    rss = true # generate rss feed. default value is false
    googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default

    css = ["css/custom.css"]
    description = "Hugo is a general-purpose website framework. Technically speaking, Hugo is a static site generator. Unlike systems that dynamically build a page with each visitor request, Hugo builds pages when you create or update your content. Since websites are viewed far more often than they are edited, Hugo is designed to provide an optimal viewing experience for your website’s end users and an ideal writing experience for website authors."
    mainSection = "posts"
    showAllPostsOnHomePage = false
    postsOnHomePage = 5
    tagsOverview = true
    # googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default

[[params.social]]
  name = "github"
  link = "https://github.com/nyovelt"

[[params.social]]
  name = "email"
  link = "nyovelt@outlook.com" # no need for "mailto:" at the start

[[params.social]]
  name = "telegram"
  link = "https://t.me/moe_canary" # no need for "mailto:" at the start


[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "About"
url = "https://who.aaaab3n.moe/"
weight = 2
[[menu.main]]
name = "Posts"
url = "/posts"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "Network"
url = "/networks"
weight = 5

[[menu.main]]
name = "Notes"
url = "/notes"
weight = 6

